Hotfix/faqs erweiterung 2494
charite-studium-und-lehre/feedbacktool-levelup-frontend pull request #22
Opened 2020-08-31 09:35 UTC by towma

2020-09-02 11:44 UTC, nikadomanska requested changes
Hi nochmal :) 
Ich kann diese Review leider erst morgen machen. Daher bitte noch einen Tag warten. 
Ich habe vorher schonmal zwei Fragen: 
Warum ist das in public/tutorial/src und nicht im normalen src drin? 
Und damit verbunden: warum hat das tutorial eigene styles (public/tutorial/src/styles.css) anstatt die bisherigen Bootstrap-Klassen zu verweden, die sonst in LevelUp dirn sind?

2020-09-02 17:48 UTC, towma commented
Alex hat dieses Tutorial gemacht, daher kann ich deine Fragen leider nicht antworten.
Beim letzten Treffen haben wir darüber gesprochen und habe vorgeschlagen , die HtmlSeiten in Tutorial zu RectComponeten umzuwandeln. Dafür habe ich das Tickt Numer #2558 erstellt.

2020-09-03 12:00 UTC, nikadomanska commented
@towma : Gut, dass du das schon angemerkt hast! 
Ich habe im FAQs erweitern Ticket #2494 unten ein paar Kommentare gemacht - weil der Umsetzungsprozess insgesamt nicht gut gelaufen ist. Also nicht wundern - das meiste davon richtet sich an Hannah.

2020-09-16 12:27 UTC, nikadomanska approved these changes

2020-09-16 12:29 UTC, nikadomanska commented
@towma @alex-at-charite : Diese Pull request hat ein Approve bekommen und darf gemergt werden, weil im Prozess der Realisierung von Tickets 2494 und 2483 so viel schief gelaufen ist, dass ich keinen Vorteil darin sehe, hier einzelne Codestellen zu Reviewen. Bitte lest euch meinen letzten Kommentar zu Ticket 2483 durch: https://llp-op.charite.de/projects/levelup/work_packages/2494/activity#activity-21 
LG!

2020-10-27 07:29 UTC, merged